Repository kstobiecki/WDP-2004-01, pull requests merged in 2020-04, with the labels that each got.

#9 add hover for feature boxes
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/features/FeatureBoxes/FeatureBoxes.js
Labels: changes requested

#8 assign color variables
  src/components/common/Button/Button.module.scss
  src/components/common/FeatureBox/FeatureBox.module.scss
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/features/NewFurniture/NewFurniture.module.scss
  src/components/features/ProductSearch/ProductSearch.module.scss
  src/components/layout/CompanyClaim/CompanyClaim.module.scss
  src/components/layout/Footer/Footer.module.scss
  src/components/layout/MenuBar/MenuBar.module.scss
  src/components/layout/TopBar/TopBar.module.scss
  src/styles/settings.scss
Labels: changes requested, conflicts

#26 Change effects on buttons
  src/components/common/Button/Button.js
  src/components/common/Button/Button.module.scss
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
Labels: changes requested

#28 WDP200401-27
  src/components/common/Button/Button.module.scss
  src/components/features/Gallery/Gallery.js
  src/components/features/Gallery/Gallery.module.scss
  src/components/features/Gallery/GalleryContainer.js
  src/components/features/Gallery/GalleryDetails.js
  src/components/features/Gallery/GalleryIcons.js
  src/components/features/Gallery/GalleryStatick.js
  src/components/views/Homepage/Homepage.js
  src/redux/galleryRedux.js
  src/redux/initialState.js
  src/redux/store.js
  src/styles/settings.scss
Labels: conflicts

#14 Wdp200401 5
  src/components/common/Button/Button.module.scss
  src/components/common/ProductBox/ProductBox.js
  src/redux/initialState.js
Labels: changes requested

#41 Update README.md
  README.md
Labels: bug, changes requested
